"""add email column to users table

Revision ID: 865a75ae8297
Revises: 0c36abda094e
Create Date: 2019-10-22 21:57:22.148539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865a75ae8297'
down_revision = '0c36abda094e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
